<template><div><h1 id="地图" tabindex="-1"><a class="header-anchor" href="#地图" aria-hidden="true">#</a> 地图</h1>
<p>本来使用 <a href="https://github.com/sparksuite/simplemde-markdown-editor" target="_blank" rel="noopener noreferrer">simplemde-markdown-editor<ExternalLinkIcon/></a> 作为 markdown 编辑器，但这个库很久不更新和维护了，而且还有 xss 风险。所以在 <Badge text="v3.9.3+"/> 版本之后使用 <a href="https://github.com/nhnent/tui.editor" target="_blank" rel="noopener noreferrer">tui.editor<ExternalLinkIcon/></a>作为新的编辑器，接下来所有的文档都是基于 tui.editor 它的。<a href="https://github.com/nhnent/tui.editor" target="_blank" rel="noopener noreferrer">更多内容<ExternalLinkIcon/></a>。</p>
<h2 id="获取文件" tabindex="-1"><a class="header-anchor" href="#获取文件" aria-hidden="true">#</a> 获取文件</h2>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code> <span class="token keyword">function</span> <span class="token function">download</span><span class="token punctuation">(</span><span class="token parameter">url<span class="token punctuation">,</span> filename</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token function">getBlob</span><span class="token punctuation">(</span>url<span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">blob</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token function">saveAs</span><span class="token punctuation">(</span>blob<span class="token punctuation">,</span> filename<span class="token punctuation">)</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span>
  <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>
